# database configuration
mysql_host = 127.0.0.1
mysql_user = root
mysql_password = 8305
mysql_database = crawler
mysql_port = 3306

# Number of unindexed pages required to run an indexing batch (default: 30)
batch_threshold = 30

# File path to the list of stopwords
stopword_file = config/stopwords.txt

# Time to sleep when there are not enough pending pages to trigger indexing (seconds)
poll_interval_seconds = 5
adaptive_polling = true
